force-app/main/default/objects/Competition__c/Competition__c.object-meta.xml
<CustomObject>
    <label>Competition</label>
    <nameField>
        <label>Competition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>    
</CustomObject>

force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <label>Match</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Competition__c.field-meta.xml
<CustomField>
    <fullName>Competition__c</fullName>
    <label>Competition</label>
    <referenceTo>Competition__c</referenceTo>
    <relationshipLabel>Competitions</relationshipLabel>
    <relationshipName>Competitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/MatchComplete__c.field-meta.xml
<CustomField>
    <fullName>MatchComplete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked (set to true) when match ended and all statistics completed</description>
    <label>Match Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Referee__c.field-meta.xml
<CustomField>
    <fullName>Referee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Match Referee</label>
    <referenceTo>Referee__c</referenceTo>
    <relationshipLabel>Ref</relationshipLabel>
    <relationshipName>Ref</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MatchStatistic__c/MatchStatistic__c.object-meta.xml
<CustomObject>
    <label>MatchStatistic</label>
    <nameField>
        <displayFormat>MatchStatistic - {000000}</displayFormat>
        <label>MatchStatistic</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MatchStatistics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MatchStatistic__c/fields/Match__c.field-meta.xml
<CustomField>
    <fullName>Match__c</fullName>
    <label>Match</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>You should choose team that participate in this match.</errorMessage>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>Match__c.HomeTeam__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>Match__c.Visitors__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Match__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MatchStatistic__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referee__c/Referee__c.object-meta.xml
<CustomObject>
    <label>Referee</label>
    <nameField>
        <label>Referee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referees</pluralLabel>
    <sharingModel>Private</sharingModel>    
</CustomObject>

force-app/main/default/objects/Referee__c/fields/Fouls__c.field-meta.xml
<CustomField>
    <fullName>Fouls__c</fullName>
    <label>Fouls Recorded Per Game</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Referee__c/fields/RedCards__c.field-meta.xml
<CustomField>
    <fullName>RedCards__c</fullName>
    <label>Red Cards Show Per Game</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Referee__c/fields/YellowCards__c.field-meta.xml
<CustomField>
    <fullName>YellowCards__c</fullName>
    <label>Yellow Cards Show Per Game</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>    
</CustomObject>

force-app/main/default/objects/TeamStatistic__c/TeamStatistic__c.object-meta.xml
<CustomObject>
    <description>Statistics of teams played matches</description>
    <label>TeamStatistic</label>
    <nameField>
        <displayFormat>TeamStatistic - {000000}</displayFormat>
        <label>TeamStatistic</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TeamStatistics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TeamStatistic__c/fields/Fouls__c.field-meta.xml
<CustomField>
    <fullName>Fouls__c</fullName>
    <description>Number of fouls completed by team in the match</description>
    <label>Fouls</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/fields/Match__c.field-meta.xml
<CustomField>
    <fullName>Match__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Match</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>Match__c.HomeTeam__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>Match__c.Visitors__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Match__c</referenceTo>
    <relationshipLabel>TeamStatistics</relationshipLabel>
    <relationshipName>TeamStatistics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/fields/Possesion__c.field-meta.xml
<CustomField>
    <fullName>Possesion__c</fullName>
    <description>Percentage of ball possession</description>
    <label>Possesion</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>TeamStatistics</relationshipLabel>
    <relationshipName>TeamStatistics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MatchTriggerHelperTest.cls
@IsTest
public class MatchTriggerHelperTest {
    
    @IsTest
    static void testRefereeStat() {
        Referee__c referee = TestDataClass.createReferee();
        Competition__c compt = TestDataClass.createCompetition();
        Team__c homeTeam = TestDataClass.createHomeTeam();
        Team__c visitorTeam = TestDataClass.createVisitorTeam();
        Match__c match = TestDataClass.createMatch(compt, referee, homeTeam, visitorTeam);
        Map<Id,Match__c> oldMap = new Map<Id,Match__c>{match.id => match};
        MatchStatistic__c[] statList = TestDataClass.refereeStats(match, homeTeam);
        List<Match__c> matches = new List<Match__c>();
        match.MatchComplete__c = true;
        matches.add(match);        
        update match;

        Test.startTest();
        MatchTriggerHelper.refereeStatistic(matches, oldMap);
        Test.stopTest();

        List<Referee__c> refList = [SELECT Fouls__c, YellowCards__c, RedCards__c FROM Referee__c WHERE Id = :referee.Id];
        for (Referee__c r: refList) {
            System.assertEquals(12, (Decimal) r.get('Fouls__c'));
            System.assertEquals(1, (Decimal) r.get('YellowCards__c'));
            System.assertEquals(0, (Decimal) r.get('RedCards__c'));
        }
    }
    
    @IsTest
    static void testTeamsStatistic() {
        Referee__c referee = TestDataClass.createReferee();
        Competition__c compt = TestDataClass.createCompetition();
        Team__c homeTeam = TestDataClass.createHomeTeam();
        Team__c visitorTeam = TestDataClass.createVisitorTeam();
        Match__c match = TestDataClass.createMatch(compt, referee, homeTeam, visitorTeam);
        Map<Id,Match__c> oldMap = new Map<Id,Match__c>{match.id => match};
        MatchStatistic__c[] homeTeamStats = TestDataClass.homeTeamStats(match, homeTeam);
        MatchStatistic__c[] visitorTeamStats = TestDataClass.visitorTeamStats(match, visitorTeam);
        List<Match__c> matches = new List<Match__c>();
        match.MatchComplete__c = true;
        matches.add(match);        
        update match;

        Test.startTest();
        MatchTriggerHelper.teamsStatistic(matches, oldMap);
        Test.stopTest();

        List<TeamStatistic__c> homeStatList = [SELECT Possesion__c FROM TeamStatistic__c WHERE Match__c = :match.Id AND Team__c = :homeTeam.id];
        for (TeamStatistic__c hs: homeStatList) {
            System.assertEquals(60, (Decimal) hs.get('Possesion__c'));
        }
        List<TeamStatistic__c> visitorStatList = [SELECT Possesion__c FROM TeamStatistic__c WHERE Match__c = :match.Id AND Team__c = :visitorTeam.id];
        for (TeamStatistic__c vs: visitorStatList) {
            System.assertEquals(40, (Decimal) vs.get('Possesion__c'));
        }
    }
}

   