force-app/main/default/objects/Competition__c/Competition__c.object-meta.xml
<CustomObject>
    <label>Competition</label>
    <nameField>
        <label>Competition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>    
</CustomObject>

force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <label>Match</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Competition__c.field-meta.xml
<CustomField>
    <fullName>Competition__c</fullName>
    <label>Competition</label>
    <referenceTo>Competition__c</referenceTo>
    <relationshipLabel>Competitions</relationshipLabel>
    <relationshipName>Competitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Referee__c.field-meta.xml
<CustomField>
    <fullName>Referee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Match Referee</label>
    <referenceTo>Referee__c</referenceTo>
    <relationshipLabel>Ref</relationshipLabel>
    <relationshipName>Ref</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MatchStatistic__c/MatchStatistic__c.object-meta.xml
<CustomObject>
    <label>MatchStatistic</label>
    <nameField>
        <displayFormat>MatchStatistic - {000000}</displayFormat>
        <label>MatchStatistic</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MatchStatistics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MatchStatistic__c/fields/Match__c.field-meta.xml
<CustomField>
    <fullName>Match__c</fullName>
    <label>Match</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>You should choose team that participate in this match.</errorMessage>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>Match__c.HomeTeam__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>Match__c.Visitors__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Match__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MatchStatistic__c/fields/Minute__c.field-meta.xml
<CustomField>
    <fullName>Minute__c</fullName>
    <label>Minute of event</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MatchStatistic__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referee__c/Referee__c.object-meta.xml
<CustomObject>
    <label>Referee</label>
    <nameField>
        <label>Referee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referees</pluralLabel>
    <sharingModel>Private</sharingModel>    
</CustomObject>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>    
</CustomObject>

force-app/main/default/objects/TeamGoals__c/TeamGoals__c.object-meta.xml
<CustomObject>
    <description>Object represent goals scored and conceded by each team</description>
    <label>Team Goals</label>
    <nameField>
        <displayFormat>TeamGoals - {000000}</displayFormat>
        <label>Team Goals Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TeamGoals__c/fields/GoalDetails__c.field-meta.xml
<CustomField>
    <fullName>GoalDetails__c</fullName>
    <description>Information if goal was scored after a corner, free kick, penalty or after a partner`s pass</description>
    <label>Goal Details</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TeamGoals__c/fields/Match__c.field-meta.xml
<CustomField>
    <fullName>Match__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Match</label>
    <referenceTo>Match__c</referenceTo>
    <relationshipLabel>Teams Goals</relationshipLabel>
    <relationshipName>Teams_Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TeamGoals__c/fields/Minute__c.field-meta.xml
<CustomField>
    <fullName>Minute__c</fullName>
    <description>Minute when goal was scored</description>
    <label>Minute</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TeamGoals__c/fields/OpponentResistance__c.field-meta.xml
<CustomField>
    <fullName>OpponentResistance__c</fullName>
    <description>Opponent resistance when performing a shot on the goal</description>
    <label>Opponent Resistance</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TeamGoals__c/fields/PlayerPosition__c.field-meta.xml
<CustomField>
    <fullName>PlayerPosition__c</fullName>
    <description>The position of the player during the shot on the goal</description>
    <label>Player Position</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TeamGoals__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Teams Goals</relationshipLabel>
    <relationshipName>Teams_Goals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/TeamStatistic__c.object-meta.xml
<CustomObject>
    <description>Statistics of teams played matches</description>
    <label>TeamStatistic</label>
    <nameField>
        <displayFormat>TeamStatistic - {000000}</displayFormat>
        <label>TeamStatistic</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TeamStatistics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TeamStatistic__c/fields/Match__c.field-meta.xml
<CustomField>
    <fullName>Match__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Match</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>Match__c.HomeTeam__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>Match__c.Visitors__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Match__c</referenceTo>
    <relationshipLabel>TeamStatistics</relationshipLabel>
    <relationshipName>TeamStatistics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>TeamStatistics</relationshipLabel>
    <relationshipName>TeamStatistics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/fields/TeamGoals__c.field-meta.xml
<CustomField>
    <fullName>TeamGoals__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Team Goals</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TeamStatisticTriggerHelperTest.cls
@IsTest
public class TeamStatisticTriggerHelperTest {

    @IsTest
    static void testTeamGoals() {
        Referee__c referee = TestDataClass.createReferee();
        Competition__c compt = TestDataClass.createCompetition();
        Team__c homeTeam = TestDataClass.createHomeTeam();
        Team__c visitorTeam = TestDataClass.createVisitorTeam();
        Match__c match = TestDataClass.createMatch(compt, referee, homeTeam, visitorTeam);
        MatchStatistic__c[] homeTeamGoals = TestDataClass.homeTeamGoalStats(match, homeTeam);
        TeamStatistic__c[] teamStatList = TestDataClass.teamStatList(match, homeTeam, visitorTeam);
        
        Test.startTest();
        TeamStatisticTriggerHelper.teamGoals(teamStatList);
        Test.stopTest();

        List<TeamGoals__c> teamGoals = [
            SELECT Minute__c, PlayerPosition__c, OpponentResistance__c 
            FROM TeamGoals__c 
            WHERE Match__c = :match.id AND Team__c = :homeTeam.id AND Minute__c = 36];
        for (TeamGoals__c tgs: teamGoals) {
            System.assertEquals('Penalty Area', (String) tgs.get('PlayerPosition__c'));
            System.assertEquals('Medium', (String) tgs.get('OpponentResistance__c'));            
        }
        
        List<TeamGoals__c> teamGoalsAssist = [
            SELECT Minute__c, PlayerPosition__c, OpponentResistance__c, GoalDetails__c 
            FROM TeamGoals__c 
            WHERE Match__c = :match.id AND Team__c = :homeTeam.id  AND Minute__c = 47];
        for (TeamGoals__c tgs: teamGoalsAssist) {
            System.assertEquals('Goal After Teammate Pass', (String) tgs.get('GoalDetails__c'));
        }
        List<TeamGoals__c> teamGoalsCorner = [
            SELECT Minute__c, PlayerPosition__c, OpponentResistance__c, GoalDetails__c 
            FROM TeamGoals__c 
            WHERE Match__c = :match.id AND Team__c = :homeTeam.id  AND Minute__c = 58];
        for (TeamGoals__c tgs: teamGoalsCorner) {
            System.assertEquals('Goal After Corner Or Fre Kick', (String) tgs.get('GoalDetails__c'));         
        }
        List<TeamGoals__c> teamGoalsPenalty = [
            SELECT Minute__c, PlayerPosition__c, OpponentResistance__c, GoalDetails__c 
            FROM TeamGoals__c 
            WHERE Match__c = :match.id AND Team__c = :homeTeam.id  AND Minute__c = 89];
        for (TeamGoals__c tgs: teamGoalsPenalty) {
            System.assertEquals('Goal After Penalty Kick', (String) tgs.get('GoalDetails__c'));       
        }
    }
}