force-app/main/default/objects/Competition__c/Competition__c.object-meta.xml
<CustomObject>
    <label>Competition</label>
    <nameField>
        <label>Competition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>    
</CustomObject>

force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <label>Match</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Competition__c.field-meta.xml
<CustomField>
    <fullName>Competition__c</fullName>
    <label>Competition</label>
    <referenceTo>Competition__c</referenceTo>
    <relationshipLabel>Competitions</relationshipLabel>
    <relationshipName>Competitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Referee__c.field-meta.xml
<CustomField>
    <fullName>Referee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Match Referee</label>
    <referenceTo>Referee__c</referenceTo>
    <relationshipLabel>Ref</relationshipLabel>
    <relationshipName>Ref</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referee__c/Referee__c.object-meta.xml
<CustomObject>
    <label>Referee</label>
    <nameField>
        <label>Referee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referees</pluralLabel>
    <sharingModel>Private</sharingModel>    
</CustomObject>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>    
</CustomObject>

force-app/main/default/objects/TeamStatistic__c/TeamStatistic__c.object-meta.xml
<CustomObject>
    <description>Statistics of teams played matches</description>
    <label>TeamStatistic</label>
    <nameField>
        <displayFormat>TeamStatistic - {000000}</displayFormat>
        <label>TeamStatistic</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TeamStatistics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TeamStatistic__c/fields/Match__c.field-meta.xml
<CustomField>
    <fullName>Match__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Match</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>Match__c.HomeTeam__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>Match__c.Visitors__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Match__c</referenceTo>
    <relationshipLabel>TeamStatistics</relationshipLabel>
    <relationshipName>TeamStatistics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>TeamStatistics</relationshipLabel>
    <relationshipName>TeamStatistics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/teamDisciplineTest.cls
@IsTest
public class teamDisciplineTest {

    @IsTest
    static void testTeamFoulsStat() {
        Referee__c referee = TestDataClass.createReferee();
        Competition__c compt = TestDataClass.createCompetition();
        Team__c homeTeam = TestDataClass.createHomeTeam();
        Team__c visitorTeam = TestDataClass.createVisitorTeam();
        Match__c match = TestDataClass.createMatch(compt, referee, homeTeam, visitorTeam);
        TeamStatistic__c[] teamStatList = TestDataClass.teamStatList(match, homeTeam, visitorTeam);
        String str = match.id;

        Test.startTest();
        List<TeamStatistic__c> teamStat = teamDiscipline.getTeamFoulsStat(str);
        Test.stopTest();
        
        System.assertEquals(2, teamStat.size());


    }
}