force-app/main/default/objects/Competition__c/Competition__c.object-meta.xml
<CustomObject>
    <label>Competition</label>
    <nameField>
        <label>Competition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>    
</CustomObject>

force-app/main/default/objects/Competition__c/fields/CompetitionType__c.field-meta.xml
<CustomField>
    <fullName>CompetitionType__c</fullName>
    <label>Competition Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Club</fullName>
                <default>true</default>
                <label>Club Competition</label>
            </value>
            <value>
                <fullName>International</fullName>
                <label>International Competition</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Competition__c/fields/Organizer__c.field-meta.xml
<CustomField>
    <fullName>Organizer__c</fullName>
    <label>Tournament Organizer</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CompetitionType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UEFA</fullName>
            </value>
            <value>
                <fullName>FIFA</fullName>
            </value>
            <value>
                <fullName>Royal Spanish Football Federation</fullName>
            </value>
            <value>
                <fullName>German Football Association</fullName>
            </value>
            <value>
                <fullName>English Football Association</fullName>
            </value>
            <value>
                <fullName>Italian Football Federation</fullName>
            </value>
            <value>
                <fullName>French Football Federation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Competition__c/fields/TournamentName__c.field-meta.xml
<CustomField>
    <fullName>TournamentName__c</fullName>
    <label>Tournament Name</label>
    <required>true</required>
    <type>Picklist</type>    
    <valueSet>
        <controllingField>TournamentType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Champions League 19/20</fullName>
            </value>
            <value>
                <fullName>Champions League 20/21</fullName>
            </value>
            <value>
                <fullName>Europa League 19/20</fullName>
            </value>
            <value>
                <fullName>Europa League 20/21</fullName>
            </value>
            <value>
                <fullName>La Liga 19/20</fullName>
            </value>
            <value>
                <fullName>La Liga 20/21</fullName>
            </value>
            <value>
                <fullName>Copa Del Rey 19/20</fullName>
            </value>
            <value>
                <fullName>Copa Del Rey 20/21</fullName>
            </value>
            <value>
                <fullName>Bundesliga 19/20</fullName>
            </value>
            <value>
                <fullName>Bundesliga 20/21</fullName>
            </value>
            <value>
                <fullName>DFB Cup 19/20</fullName>
            </value>
            <value>
                <fullName>DFB Cup 20/21</fullName>
            </value>
            <value>
                <fullName>Premier League 19/20</fullName>
            </value>
            <value>
                <fullName>Premier League 20/21</fullName>
            </value>
            <value>
                <fullName>FA Cup 19/20</fullName>
            </value>
            <value>
                <fullName>FA Cup 20/21</fullName>
            </value>
            <value>
                <fullName>Serie A 19/20</fullName>
            </value>
            <value>
                <fullName>Serie A 20/21</fullName>
            </value>
            <value>
                <fullName>Coppa Italia 19/20</fullName>
            </value>
            <value>
                <fullName>Coppa Italia 20/21</fullName>
            </value>
            <value>
                <fullName>Ligue 1 19/20</fullName>
            </value>
            <value>
                <fullName>Ligue 1 20/21</fullName>
            </value>
            <value>
                <fullName>France Cup 19/20</fullName>
            </value>
            <value>
                <fullName>France Cup 20/21</fullName>
            </value>
            <value>
                <fullName>Euro 2020</fullName>
            </value>
            <value>
                <fullName>World Cup 2022</fullName>
            </value>
            <value>
                <fullName>Friendly Match</fullName>
            </value>
        </valueSetDefinition>             
    </valueSet>
</CustomField>

force-app/main/default/objects/Competition__c/fields/TournamentType__c.field-meta.xml
<CustomField>
    <fullName>TournamentType__c</fullName>
    <label>Tournament Type</label>
    <required>true</required>
    <type>Picklist</type>    
    <valueSet>
        <controllingField>Organizer__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Champions League</fullName>
            </value>
            <value>
                <fullName>Europa League</fullName>
            </value>
            <value>
                <fullName>Championship</fullName>
            </value>
            <value>
                <fullName>Cup</fullName>
            </value>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>Main Tournament</fullName>
            </value>
            <value>
                <fullName>Friendly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <label>Match</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Competition__c.field-meta.xml
<CustomField>
    <fullName>Competition__c</fullName>
    <label>Competition</label>
    <referenceTo>Competition__c</referenceTo>
    <relationshipLabel>Competitions</relationshipLabel>
    <relationshipName>Competitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Referee__c.field-meta.xml
<CustomField>
    <fullName>Referee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Match Referee</label>
    <referenceTo>Referee__c</referenceTo>
    <relationshipLabel>Ref</relationshipLabel>
    <relationshipName>Ref</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MatchStatistic__c/MatchStatistic__c.object-meta.xml
<CustomObject>
    <label>MatchStatistic</label>
    <nameField>
        <displayFormat>MatchStatistic - {000000}</displayFormat>
        <label>MatchStatistic</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MatchStatistics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MatchStatistic__c/fields/Match__c.field-meta.xml
<CustomField>
    <fullName>Match__c</fullName>
    <label>Match</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>You should choose team that participate in this match.</errorMessage>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>Match__c.HomeTeam__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>Match__c.Visitors__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Match__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MatchStatistic__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referee__c/Referee__c.object-meta.xml
<CustomObject>
    <label>Referee</label>
    <nameField>
        <label>Referee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referees</pluralLabel>
    <sharingModel>Private</sharingModel>    
</CustomObject>

force-app/main/default/objects/Referee__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country Referee From</label>    
    <required>true</required>
    <type>Text</type>
    <length>36</length>
</CustomField>

force-app/main/default/objects/Referee__c/fields/Fouls__c.field-meta.xml
<CustomField>
    <fullName>Fouls__c</fullName>
    <label>Fouls Recorded Per Game</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Referee__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Referee Name</label>    
    <required>true</required>
    <type>Text</type>
    <length>36</length>
</CustomField>

force-app/main/default/objects/Referee__c/fields/RedCards__c.field-meta.xml
<CustomField>
    <fullName>RedCards__c</fullName>
    <label>Red Cards Show Per Game</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Referee__c/fields/YellowCards__c.field-meta.xml
<CustomField>
    <fullName>YellowCards__c</fullName>
    <label>Yellow Cards Show Per Game</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>    
</CustomObject>

force-app/main/default/objects/Team__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>    
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>England</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Scotland</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Ukraine</fullName>
                <default>true</default>
                <label>Ukraine</label>
            </value>
            <value>
                <fullName>Portugal</fullName>
            </value>
            <value>
                <fullName>Turkey</fullName>
            </value>
            <value>
                <fullName>Romania</fullName>
            </value>
            <value>
                <fullName>Cyprus</fullName>
            </value>
            <value>
                <fullName>Switzerland</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Team Name</label>    
    <required>true</required>
    <type>Text</type>
    <length>68</length>
</CustomField>

force-app/main/default/objects/Team__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Team Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Club</fullName>
                <default>true</default>
                <label>Club Team</label>
            </value>
            <value>
                <fullName>International</fullName>
                <label>International Team</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/TeamStatistic__c.object-meta.xml
<CustomObject>
    <description>Statistics of teams played matches</description>
    <label>TeamStatistic</label>
    <nameField>
        <displayFormat>TeamStatistic - {000000}</displayFormat>
        <label>TeamStatistic</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TeamStatistics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TeamStatistic__c/fields/Fouls__c.field-meta.xml
<CustomField>
    <fullName>Fouls__c</fullName>
    <description>Number of fouls completed by team in the match</description>
    <label>Fouls</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>TeamStatistics</relationshipLabel>
    <relationshipName>TeamStatistics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestDataClass.cls
@isTest
public class TestDataClass {

    public static Referee__c createReferee() {
        Referee__c referee = new Referee__c(
            Name__c = 'Test', 
            Country__c = 'Ukraine', 
            Fouls__c = 0,
            YellowCards__c = 0,
            RedCards__c = 0);
        insert referee;
        return referee;
    }

    public static Competition__c createCompetition() {
        Competition__c compt = new Competition__c(
            CompetitionType__c = 'Club',
            Organizer__c = 'UEFA',
            TournamentType__c = 'Champions League',
            TournamentName__c = 'Champions League 19/20'
        );
        insert compt;
        return compt;
    }

    public static Team__c createHomeTeam() {
        Team__c homeTeam = new Team__c(Name__c = 'Home', Type__c = 'Club Team');
        insert homeTeam;
        return homeTeam;
    }

    public static Team__c createVisitorTeam() {
        Team__c visitorTeam = new Team__c(Name__c = 'Visitor', Type__c = 'Club Team');
        insert visitorTeam;
        return visitorTeam;
    }
    
    public static Match__c createMatch(Competition__c compt, Referee__c referee, Team__c homeTeam, Team__c visitorTeam) {
        Match__c match = new Match__c(
            Competition__c = compt.Id,
            Referee__c = referee.Id,
            StartDateTime__c = Datetime.newInstance(Date.parse('27/12/2019'), Time.newInstance(18, 0, 0, 0)),
            HomeTeam__c = homeTeam.Id,
            Visitors__c = visitorTeam.Id,
            MatchComplete__c = false
        );
        insert match;
        return match;
    }

    public static List<MatchStatistic__c> visitorTeamStats(Match__c match, Team__c visitorTeam) {
        List<MatchStatistic__c> statList = new List<MatchStatistic__c>();
        MatchStatistic__c stat1 = new MatchStatistic__c(
            Match__c = match.id,
            Team__c = visitorTeam.id,
            EventType__c = 'Possesion',
            EventValue__c = 40
        );
        statList.add(stat1);
        MatchStatistic__c stat2 = new MatchStatistic__c(
            Match__c = match.id,
            Team__c = visitorTeam.id,
            EventType__c = 'Fouls',
            EventValue__c = 21
        );
        statList.add(stat2);
        MatchStatistic__c stat3 = new MatchStatistic__c(
            Match__c = match.id,
            Team__c = visitorTeam.id,
            EventType__c = 'Corners',
            EventValue__c = 4
        );
        statList.add(stat3);
        insert statList;
        return statList;
    }

    public static List<MatchStatistic__c> homeTeamStats (Match__c match, Team__c homeTeam) {
        List<MatchStatistic__c> statList = new List<MatchStatistic__c>();
        MatchStatistic__c stat1 = new MatchStatistic__c(
            Match__c = match.id,
            Team__c = homeTeam.id,
            EventType__c = 'Possesion',
            EventValue__c = 60
        );
        statList.add(stat1);
        MatchStatistic__c stat2 = new MatchStatistic__c(
            Match__c = match.id,
            Team__c = homeTeam.id,
            EventType__c = 'Fouls',
            EventValue__c = 13
        );
        statList.add(stat2);
        MatchStatistic__c stat3 = new MatchStatistic__c(
            Match__c = match.id,
            Team__c = homeTeam.id,
            EventType__c = 'Corners',
            EventValue__c = 8
        );
        statList.add(stat3);
        insert statList;
        return statList;
    }

    public static List<MatchStatistic__c> refereeStats (Match__c match, Team__c homeTeam) {
        List<MatchStatistic__c> statList = new List<MatchStatistic__c>();
        MatchStatistic__c stat1 = new MatchStatistic__c(
            Match__c = match.id,
            Team__c = homeTeam.id,
            EventType__c = 'Fouls',
            EventValue__c = 12
        );
        statList.add(stat1);
        MatchStatistic__c stat2 = new MatchStatistic__c(
            Match__c = match.id,
            Team__c = homeTeam.id,
            EventType__c = 'Yellow Card',
            EventValue__c = 1
        );
        statList.add(stat2);
        MatchStatistic__c stat3 = new MatchStatistic__c(
            Match__c = match.id,
            Team__c = homeTeam.id,
            EventType__c = 'Red Card',
            EventValue__c = 0
        );
        statList.add(stat3);
        insert statList;
        return statList;
    }

    public static List<MatchStatistic__c> homeTeamGoalStats (Match__c match, Team__c homeTeam) {
        List<MatchStatistic__c> statList = new List<MatchStatistic__c>();
        MatchStatistic__c stat1 = new MatchStatistic__c(
            Match__c = match.id,
            Team__c = homeTeam.id,
            EventType__c = 'Shot',
            GoalkeeperAction__c = '3',
            Minute__c = 36,
            ShotPosition__c = 'Penalty Area',
            ShotResistance__c = 'Medium'
        );
        statList.add(stat1);
        MatchStatistic__c stat2 = new MatchStatistic__c(
            Match__c = match.id,
            Team__c = homeTeam.id,
            EventType__c = 'Shot',
            GoalkeeperAction__c = '3',
            Minute__c = 47,
            ShotPosition__c = 'Penalty Area',
            ShotResistance__c = 'Medium',
            Assist__c = true
        );
        statList.add(stat2);
        MatchStatistic__c stat3 = new MatchStatistic__c(
            Match__c = match.id,
            Team__c = homeTeam.id,
            EventType__c = 'Shot',
            GoalkeeperAction__c = '3',
            Minute__c = 68,
            ShotPosition__c = 'Penalty Area',
            ShotResistance__c = 'Medium',
            CornerOrFreeKick__c = true
        );
        statList.add(stat3);
        MatchStatistic__c stat4 = new MatchStatistic__c(
            Match__c = match.id,
            Team__c = homeTeam.id,
            EventType__c = 'Shot',
            GoalkeeperAction__c = '3',
            Minute__c = 89,
            ShotPosition__c = 'Penalty Area',
            ShotResistance__c = 'Medium',
            Penalti__c = true
        );
        statList.add(stat4);
        insert statList;
        return statList;
    }
    
    public static List<MatchStatistic__c> visitorTeamGoalStats (Match__c match, Team__c visitorTeam) {
        List<MatchStatistic__c> statList = new List<MatchStatistic__c>();
        MatchStatistic__c stat1 = new MatchStatistic__c(
            Match__c = match.id,
            Team__c = visitorTeam.id,
            EventType__c = 'Shot',
            GoalkeeperAction__c = '3',
            Minute__c = 36,
            ShotPosition__c = 'Penalty Area',
            ShotResistance__c = 'Medium'
        );
        statList.add(stat1);
        MatchStatistic__c stat2 = new MatchStatistic__c(
            Match__c = match.id,
            Team__c = visitorTeam.id,
            EventType__c = 'Shot',
            GoalkeeperAction__c = '3',
            Minute__c = 47,
            ShotPosition__c = 'Penalty Area',
            ShotResistance__c = 'Medium',
            Assist__c = true
        );
        statList.add(stat2);
        MatchStatistic__c stat3 = new MatchStatistic__c(
            Match__c = match.id,
            Team__c = visitorTeam.id,
            EventType__c = 'Shot',
            GoalkeeperAction__c = '3',
            Minute__c = 68,
            ShotPosition__c = 'Penalty Area',
            ShotResistance__c = 'Medium',
            CornerOrFreeKick__c = true
        );
        statList.add(stat3);        
        insert statList;
        return statList;
    }

    public static List<TeamStatistic__c> teamStatList(Match__c match, Team__c homeTeam, Team__c visitorTeam) {
        List<TeamStatistic__c> teamStatList = new List<TeamStatistic__c>();
        TeamStatistic__c teamStat1 = new TeamStatistic__c(
            Match__c = match.id,
            Team__c = homeTeam.id,
            Fouls__c = 36
        );
        teamStatList.add(teamStat1);
        TeamStatistic__c teamStat2 = new TeamStatistic__c(
            Match__c = match.id,
            Team__c = visitorTeam.id,
            Fouls__c = 36
        );
        teamStatList.add(teamStat2);
        insert teamStatList;
        return teamStatList;
    }
}