force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <label>Match</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/HomeGol__c.field-meta.xml
<CustomField>
    <fullName>HomeGol__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Home Team Goals</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/HomeTeam__c.field-meta.xml
<CustomField>
    <fullName>HomeTeam__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Home Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Hosts</relationshipLabel>
    <relationshipName>Hosts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/MatchComplete__c.field-meta.xml
<CustomField>
    <fullName>MatchComplete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked (set to true) when match ended and all statistics completed</description>
    <label>Match Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Referee__c.field-meta.xml
<CustomField>
    <fullName>Referee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Match Referee</label>
    <referenceTo>Referee__c</referenceTo>
    <relationshipLabel>Ref</relationshipLabel>
    <relationshipName>Ref</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Match Start Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/VisitorGol__c.field-meta.xml
<CustomField>
    <fullName>VisitorGol__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Visitor Team Goals</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Visitors__c.field-meta.xml
<CustomField>
    <fullName>Visitors__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Visitor Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Visitor</relationshipLabel>
    <relationshipName>Visitor</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MatchStatistic__c/MatchStatistic__c.object-meta.xml
<CustomObject>
    <label>MatchStatistic</label>
    <nameField>
        <displayFormat>MatchStatistic - {000000}</displayFormat>
        <label>MatchStatistic</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MatchStatistics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MatchStatistic__c/fields/EventType__c.field-meta.xml
<CustomField>
    <fullName>EventType__c</fullName>
    <label>Type of Event</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Shot</fullName>
            </value>
            <value>
                <fullName>Total Shots</fullName>
            </value>
            <value>
                <fullName>Shots On Target</fullName>
            </value>
            <value>
                <fullName>Possesion</fullName>
                <default>true</default>
                <label>Possesion</label>
            </value>
            <value>
                <fullName>Total Passes</fullName>
            </value>
            <value>
                <fullName>Completed Passes</fullName>
            </value>
            <value>
                <fullName>Fouls</fullName>
            </value>
            <value>
                <fullName>Yellow Card</fullName>
            </value>
            <value>
                <fullName>Red Card</fullName>
            </value>
            <value>
                <fullName>Offsides</fullName>
            </value>
            <value>
                <fullName>Corners</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MatchStatistic__c/fields/EventValue__c.field-meta.xml
<CustomField>
    <fullName>EventValue__c</fullName>
    <label>Value of statistical index</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MatchStatistic__c/fields/Match__c.field-meta.xml
<CustomField>
    <fullName>Match__c</fullName>
    <label>Match</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>You should choose team that participate in this match.</errorMessage>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>Match__c.HomeTeam__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>Match__c.Visitors__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Match__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MatchStatistic__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referee__c/Referee__c.object-meta.xml
<CustomObject>
    <label>Referee</label>
    <nameField>
        <label>Referee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referees</pluralLabel>
    <sharingModel>Private</sharingModel>    
</CustomObject>

force-app/main/default/objects/Referee__c/fields/Fouls__c.field-meta.xml
<CustomField>
    <fullName>Fouls__c</fullName>
    <label>Fouls Recorded Per Game</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Referee__c/fields/RedCards__c.field-meta.xml
<CustomField>
    <fullName>RedCards__c</fullName>
    <label>Red Cards Show Per Game</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Referee__c/fields/YellowCards__c.field-meta.xml
<CustomField>
    <fullName>YellowCards__c</fullName>
    <label>Yellow Cards Show Per Game</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>    
</CustomObject>

force-app/main/default/objects/TeamGoals__c/TeamGoals__c.object-meta.xml
<CustomObject>
    <description>Object represent goals scored and conceded by each team</description>
    <label>Team Goals</label>
    <nameField>
        <displayFormat>TeamGoals - {000000}</displayFormat>
        <label>Team Goals Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TeamGoals__c/fields/Match__c.field-meta.xml
<CustomField>
    <fullName>Match__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Match</label>
    <referenceTo>Match__c</referenceTo>
    <relationshipLabel>Teams Goals</relationshipLabel>
    <relationshipName>Teams_Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TeamGoals__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Teams Goals</relationshipLabel>
    <relationshipName>Teams_Goals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/TeamStatistic__c.object-meta.xml
<CustomObject>
    <description>Statistics of teams played matches</description>
    <label>TeamStatistic</label>
    <nameField>
        <displayFormat>TeamStatistic - {000000}</displayFormat>
        <label>TeamStatistic</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TeamStatistics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TeamStatistic__c/fields/CompletedPasses__c.field-meta.xml
<CustomField>
    <fullName>CompletedPasses__c</fullName>
    <description>Number of accurate passes made by team in the match</description>
    <label>Completed Passes</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/fields/Corners__c.field-meta.xml
<CustomField>
    <fullName>Corners__c</fullName>
    <description>Number of corner kicks made by team in the match</description>
    <label>Corners</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/fields/Fouls__c.field-meta.xml
<CustomField>
    <fullName>Fouls__c</fullName>
    <description>Number of fouls completed by team in the match</description>
    <label>Fouls</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/fields/Match__c.field-meta.xml
<CustomField>
    <fullName>Match__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Match</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>Match__c.HomeTeam__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>Match__c.Visitors__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Match__c</referenceTo>
    <relationshipLabel>TeamStatistics</relationshipLabel>
    <relationshipName>TeamStatistics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/fields/Offsides__c.field-meta.xml
<CustomField>
    <fullName>Offsides__c</fullName>
    <description>Number of offsides recorded by team in the match</description>
    <label>Offsides</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/fields/OpponentGoals__c.field-meta.xml
<CustomField>
    <fullName>OpponentGoals__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Opponent Goals</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/fields/Possesion__c.field-meta.xml
<CustomField>
    <fullName>Possesion__c</fullName>
    <description>Percentage of ball possession</description>
    <label>Possesion</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/fields/RedCard__c.field-meta.xml
<CustomField>
    <fullName>RedCard__c</fullName>
    <description>Number of received red cards in the match</description>
    <label>Red Card</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/fields/ShotsOnTarget__c.field-meta.xml
<CustomField>
    <fullName>ShotsOnTarget__c</fullName>
    <description>Number of shots on target that team made in match</description>
    <label>Shots On Target</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>TeamStatistics</relationshipLabel>
    <relationshipName>TeamStatistics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/fields/TeamGoals__c.field-meta.xml
<CustomField>
    <fullName>TeamGoals__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Team Goals</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/fields/TotalPasses__c.field-meta.xml
<CustomField>
    <fullName>TotalPasses__c</fullName>
    <description>Number of passes made by team in the match</description>
    <label>Total Passes</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/fields/TotalShots__c.field-meta.xml
<CustomField>
    <fullName>TotalShots__c</fullName>
    <description>Number of shots that team made in match</description>
    <label>Total Shots</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/fields/YellowCard__c.field-meta.xml
<CustomField>
    <fullName>YellowCard__c</fullName>
    <description>Number of received yellow cards in the match</description>
    <label>Yellow Card</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MatchTriggerHelper.cls
public class MatchTriggerHelper {

    public static void refereeStatistic (List<Match__c> matches) {
        Set<Id> refIds = new Set<Id>();
        List<Referee__c> refList = new List<Referee__c>();
        Map<Id, Decimal> avgRefFouls = new Map<Id, Decimal>();
        Map<Id, Decimal> avgRefYellows = new Map<Id, Decimal>();
        Map<Id, Decimal> avgRefReds = new Map<Id, Decimal>();
        // Build Set with Id`s of referees
        for (Match__c match: matches) {
            refIds.add(match.Referee__c);
        }
        // Return if referees not found (Set refIds is empty)
        if(refIds.isEmpty()) {
            return;
        }
        // List of matches in which referee participate
        List<Match__c> matchList = [
            SELECT StartDateTime__c
            FROM Match__c
            WHERE Referee__c IN :refIds];
        // Count total fouls commited in matches which referee participate
        List<AggregateResult> refFouls = [
            SELECT SUM(EventValue__c) fouls, Match__r.Referee__c ref
            FROM MatchStatistic__c 
            WHERE Match__r.Referee__c IN :refIds AND EventType__c = 'Fouls'
            GROUP BY Match__r.Referee__c];
            // Add referee Id and average fouls to map
            for(AggregateResult aggRes :refFouls) {
                avgRefFouls.put((Id)aggRes.get('ref'), (Decimal) aggRes.get('fouls') / matchList.size());
            }
        // Count total yellow cards show in matches which referee participate 
        List<AggregateResult> refYellows = [
            SELECT SUM(EventValue__c) yellows, Match__r.Referee__c ref
            FROM MatchStatistic__c 
            WHERE Match__r.Referee__c IN :refIds AND EventType__c = 'Yellow Card'
            GROUP BY Match__r.Referee__c];
            // Add referee Id and average yellow cards to map
            for(AggregateResult aggRes :refYellows) {
                avgRefYellows.put((Id)aggRes.get('ref'), (Decimal) aggRes.get('yellows') / matchList.size());
            }
        // Count total red cards show in matches which referee participate
        List<AggregateResult> refReds = [
            SELECT SUM(EventValue__c) reds, Match__r.Referee__c ref
            FROM MatchStatistic__c 
            WHERE Match__r.Referee__c IN :refIds AND EventType__c = 'Red Card'
            GROUP BY Match__r.Referee__c];
            // Add referee Id and average red cards to map
            for(AggregateResult aggRes :refReds) {
                avgRefReds.put((Id)aggRes.get('ref'), (Decimal) aggRes.get('reds') / matchList.size());
            }
        // Create list with updating referees
        for (Id rId: refIds) {
            refList.add(new Referee__c(Id = rId, 
            Fouls__c = avgRefFouls.get(rId), YellowCards__c = avgRefYellows.get(rId), RedCards__c = avgRefReds.get(rId)));
        }
        // Update referees
        update refList;
    }

    public static void homeTeamStatistic (List<Match__c> matches, Map<Id, Match__c> oldMap) {
        List<TeamStatistic__c> teamStat = new List<TeamStatistic__c>();
        Map<String,Decimal> homeTeamStatistic = new Map<String,Decimal>();
        Map<String,Decimal> visitorTeamStatistic = new Map<String,Decimal>();
        List<Id> matchIds = new List<Id>();
        List<Id> homeTeamIds = new List<Id>();
        List<Id> visitorTeamIds = new List<Id>();
        // Build Set with Id`s of matches, home teams and visitor teams when Match__c record update
        for (Match__c match :matches) {
            if (match.MatchComplete__c == true) {
                matchIds.add(match.Id);
                homeTeamIds.add(match.HomeTeam__c);
                visitorTeamIds.add(match.Visitors__c);
            }
        }
        // Find home team statistics for selected matches
        List<MatchStatistic__c> homeTeamStats = [
            SELECT EventType__c, EventValue__c
            FROM MatchStatistic__c
            WHERE Match__c IN :matchIds AND Team__c IN :homeTeamIds AND EventType__c != 'Shot'
        ];
        // Create map with type and value of statistic indexes for home teams
        for (MatchStatistic__c homeStat: homeTeamStats) {
            homeTeamStatistic.put((String)homeStat.get('EventType__c'), (Decimal)homeStat.get('EventValue__c'));
        }
        // Find visitor team statistics for selected matches
        List<MatchStatistic__c> visitorTeamStats = [
            SELECT EventType__c, EventValue__c
            FROM MatchStatistic__c
            WHERE Match__c IN :matchIds AND Team__c IN :visitorTeamIds AND EventType__c != 'Shot'
        ];
        // Create map with type and value of statistic indexes for home teams
        for (MatchStatistic__c visitorStat: visitorTeamStats) {
            visitorTeamStatistic.put((String)visitorStat.get('EventType__c'), (Decimal)visitorStat.get('EventValue__c'));
        }
        // Create list with inserting team statistic if the MatchComplete__c field set to true
        for (Match__c m :matches) {        
            if (m.MatchComplete__c == true && oldMap.get(m.Id).MatchComplete__c == false) {
                // Add statistic for match home team
                teamStat.add(new TeamStatistic__c(
                Match__c = m.Id, Team__c = m.HomeTeam__c, Possesion__c = homeTeamStatistic.get('Possesion'), 
                TotalShots__c = homeTeamStatistic.get('Total Shots'), ShotsOnTarget__c = homeTeamStatistic.get('Shots On Target'),
                Fouls__c = homeTeamStatistic.get('Fouls'), Corners__c = homeTeamStatistic.get('Corners'),
                TotalPasses__c = homeTeamStatistic.get('Total Passes'), CompletedPasses__c = homeTeamStatistic.get('Completed Passes'),
                YellowCard__c = homeTeamStatistic.get('Yellow Card'), RedCard__c = homeTeamStatistic.get('Red Card'),
                Offsides__c = homeTeamStatistic.get('Offsides'), TeamGoals__c = m.HomeGol__c, OpponentGoals__c = m.VisitorGol__c));
                // Add statistic for match visior team
                teamStat.add(new TeamStatistic__c(
                Match__c = m.Id, Team__c = m.Visitors__c, Possesion__c = visitorTeamStatistic.get('Possesion'), 
                TotalShots__c = visitorTeamStatistic.get('Total Shots'), ShotsOnTarget__c = visitorTeamStatistic.get('Shots On Target'),
                Fouls__c = visitorTeamStatistic.get('Fouls'), Corners__c = visitorTeamStatistic.get('Corners'),
                TotalPasses__c = visitorTeamStatistic.get('Total Passes'), CompletedPasses__c = visitorTeamStatistic.get('Completed Passes'),
                YellowCard__c = visitorTeamStatistic.get('Yellow Card'), RedCard__c = visitorTeamStatistic.get('Red Card'),
                Offsides__c = visitorTeamStatistic.get('Offsides'), TeamGoals__c = m.VisitorGol__c, OpponentGoals__c = m.HomeGol__c));
            }        
        }
        // Insert list with statistic for teams participated in match
        insert teamStat;
    }
    
}