force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <label>Match</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/HomeGol__c.field-meta.xml
<CustomField>
    <fullName>HomeGol__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Home Team Goals</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/HomeTeam__c.field-meta.xml
<CustomField>
    <fullName>HomeTeam__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Home Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Hosts</relationshipLabel>
    <relationshipName>Hosts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/VisitorGol__c.field-meta.xml
<CustomField>
    <fullName>VisitorGol__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Visitor Team Goals</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Visitors__c.field-meta.xml
<CustomField>
    <fullName>Visitors__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Visitor Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Visitor</relationshipLabel>
    <relationshipName>Visitor</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MatchStatistic__c/MatchStatistic__c.object-meta.xml
<CustomObject>
    <label>MatchStatistic</label>
    <nameField>
        <displayFormat>MatchStatistic - {000000}</displayFormat>
        <label>MatchStatistic</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MatchStatistics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MatchStatistic__c/fields/GoalkeeperAction__c.field-meta.xml
<CustomField>
    <fullName>GoalkeeperAction__c</fullName>
    <label>Goalkeeper Action After Shot</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ShotAccuracy__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
                <default>true</default>
                <label>3</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MatchStatistic__c/fields/Match__c.field-meta.xml
<CustomField>
    <fullName>Match__c</fullName>
    <label>Match</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>You should choose team that participate in this match.</errorMessage>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>Match__c.HomeTeam__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>Match__c.Visitors__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Match__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MatchStatistic__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>    
</CustomObject>

force-app/main/default/classes/MatchStatisticTriggerHelper.cls
public class MatchStatisticTriggerHelper {

    public static void teamGoals (List<MatchStatistic__c> matchStats) {
        Set<Id> matchIds = new Set<Id>();
        Set<Id> teamIds = new Set<Id>();
        List<Match__c> matchList = new List<Match__c>();
        Map<Id, Integer> teamTotGols = new Map<Id, Integer>();
        // Build Set with Id`s of matches with statistic event
        for (MatchStatistic__c mst: matchStats) {
            if (String.isNotBlank(mst.Team__c) && mst.GoalkeeperAction__c == '3') {
                matchIds.add(mst.Match__c);
                teamIds.add(mst.Team__c);           
            }
        }
        // Return if matches not found (Set matchIds is empty)
        if(matchIds.isEmpty()) {
            return;
        }
        // Count gols for each team in matches that have statistic event
        List<AggregateResult> result = [
            SELECT count(Id) gols, Team__c team
            FROM MatchStatistic__c 
            WHERE Match__c IN :matchIds AND GoalkeeperAction__c = '3' 
            GROUP BY Team__c];
        // Create map with id and number of gols for all teams
        for(AggregateResult aggRes :result) {                
            teamTotGols.put((Id)aggRes.get('team'), (Integer) aggRes.get('gols'));
        }
        // Find matches with statistic events
        List<Match__c> matches = [
            SELECT HomeTeam__c, Visitors__c, HomeGol__c, VisitorGol__c 
            FROM Match__c 
            WHERE Id IN :matchIds];
        // Create list with updating matches
        for (Match__c m: matches) {
            for (Id tId: teamIds) {
                if (tId == m.HomeTeam__c) {
                    matchList.add(new Match__c(Id = m.Id, HomeGol__c = teamTotGols.get(tId)));   
                } else {
                    matchList.add(new Match__c(Id = m.Id, VisitorGol__c = teamTotGols.get(tId)));
                }                    
            }
        }
        // Update matches
        update matchList;
    }    
}