force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <label>Match</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MatchStatistic__c/MatchStatistic__c.object-meta.xml
<CustomObject>
    <label>MatchStatistic</label>
    <nameField>
        <displayFormat>MatchStatistic - {000000}</displayFormat>
        <label>MatchStatistic</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MatchStatistics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MatchStatistic__c/fields/Assist__c.field-meta.xml
<CustomField>
    <fullName>Assist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if shot was after partner passes</description>
    <label>Shot After Assist</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MatchStatistic__c/fields/CornerOrFreeKick__c.field-meta.xml
<CustomField>
    <fullName>CornerOrFreeKick__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if shot was after corner kick or free kick</description>
    <label>Shot After Corner Kick Or Free Kick</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MatchStatistic__c/fields/EventType__c.field-meta.xml
<CustomField>
    <fullName>EventType__c</fullName>
    <label>Type of Event</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Shot</fullName>
            </value>
            <value>
                <fullName>Total Shots</fullName>
            </value>
            <value>
                <fullName>Shots On Target</fullName>
            </value>
            <value>
                <fullName>Possesion</fullName>
                <default>true</default>
                <label>Possesion</label>
            </value>
            <value>
                <fullName>Total Passes</fullName>
            </value>
            <value>
                <fullName>Completed Passes</fullName>
            </value>
            <value>
                <fullName>Fouls</fullName>
            </value>
            <value>
                <fullName>Yellow Card</fullName>
            </value>
            <value>
                <fullName>Red Card</fullName>
            </value>
            <value>
                <fullName>Offsides</fullName>
            </value>
            <value>
                <fullName>Corners</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MatchStatistic__c/fields/Match__c.field-meta.xml
<CustomField>
    <fullName>Match__c</fullName>
    <label>Match</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>You should choose team that participate in this match.</errorMessage>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>Match__c.HomeTeam__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>Match__c.Visitors__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Match__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MatchStatistic__c/fields/Minute__c.field-meta.xml
<CustomField>
    <fullName>Minute__c</fullName>
    <label>Minute of event</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MatchStatistic__c/fields/Penalti__c.field-meta.xml
<CustomField>
    <fullName>Penalti__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if shot was from penalti kick</description>
    <label>Shot From Penalti</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MatchStatistic__c/fields/ShotPosition__c.field-meta.xml
<CustomField>
    <fullName>ShotPosition__c</fullName>
    <label>Position Of Shot</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>EventType__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Outside The Box</fullName>
                <label>Outside The Penalty Area</label>
            </value>
            <value>
                <fullName>Penalty Area</fullName>
                <label>Penalty Area + Nine Meter Arc</label>
            </value>
            <value>
                <fullName>Goal Area</fullName>
                <label>Goal Area + Penalty Spot</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MatchStatistic__c/fields/ShotResistance__c.field-meta.xml
<CustomField>
    <fullName>ShotResistance__c</fullName>
    <label>Resistance To Shot</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>EventType__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
                <label>Low Resistance (distance to opponent greater than 2 metre)</label>
            </value>
            <value>
                <fullName>Medium</fullName>
                <label>Medium Resistance (distance to opponent from 1 to 2 metre)</label>
            </value>
            <value>
                <fullName>Hard</fullName>
                <label>Hard Resistance (distance to opponent less than 1 metre)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MatchStatistic__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>    
</CustomObject>

force-app/main/default/objects/TeamGoals__c/TeamGoals__c.object-meta.xml
<CustomObject>
    <description>Object represent goals scored and conceded by each team</description>
    <label>Team Goals</label>
    <nameField>
        <displayFormat>TeamGoals - {000000}</displayFormat>
        <label>Team Goals Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TeamGoals__c/fields/GoalDetails__c.field-meta.xml
<CustomField>
    <fullName>GoalDetails__c</fullName>
    <description>Information if goal was scored after a corner, free kick, penalty or after a partner`s pass</description>
    <label>Goal Details</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TeamGoals__c/fields/Match__c.field-meta.xml
<CustomField>
    <fullName>Match__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Match</label>
    <referenceTo>Match__c</referenceTo>
    <relationshipLabel>Teams Goals</relationshipLabel>
    <relationshipName>Teams_Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TeamGoals__c/fields/Minute__c.field-meta.xml
<CustomField>
    <fullName>Minute__c</fullName>
    <description>Minute when goal was scored</description>
    <label>Minute</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TeamGoals__c/fields/OpponentResistance__c.field-meta.xml
<CustomField>
    <fullName>OpponentResistance__c</fullName>
    <description>Opponent resistance when performing a shot on the goal</description>
    <label>Opponent Resistance</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TeamGoals__c/fields/PlayerPosition__c.field-meta.xml
<CustomField>
    <fullName>PlayerPosition__c</fullName>
    <description>The position of the player during the shot on the goal</description>
    <label>Player Position</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TeamGoals__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Teams Goals</relationshipLabel>
    <relationshipName>Teams_Goals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/TeamStatistic__c.object-meta.xml
<CustomObject>
    <description>Statistics of teams played matches</description>
    <label>TeamStatistic</label>
    <nameField>
        <displayFormat>TeamStatistic - {000000}</displayFormat>
        <label>TeamStatistic</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TeamStatistics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TeamStatistic__c/fields/Match__c.field-meta.xml
<CustomField>
    <fullName>Match__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Match</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>Match__c.HomeTeam__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>Match__c.Visitors__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Match__c</referenceTo>
    <relationshipLabel>TeamStatistics</relationshipLabel>
    <relationshipName>TeamStatistics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>TeamStatistics</relationshipLabel>
    <relationshipName>TeamStatistics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/fields/TeamGoals__c.field-meta.xml
<CustomField>
    <fullName>TeamGoals__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Team Goals</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TeamStatisticTriggerHelper.cls
public class TeamStatisticTriggerHelper {

    public static void teamGoals (List<TeamStatistic__c> teamStats) {
        Set<Id> matchIds = new Set<Id>();
        List<TeamGoals__c> teamGoalsList = new List<TeamGoals__c>();
        // Build Set with Id`s of matches to which tne new team statistic refer
        for (TeamStatistic__c ts: teamStats) {
            if (String.isNotBlank(ts.Match__c) && String.isNotBlank(ts.Team__c)) {
                matchIds.add(ts.Match__c);
            }
        }
        // Return if matches not found (Set matchIds is empty)
        if(matchIds.isEmpty()) {
            return;
        }
        // Find goal statistics for selected matches
        List<MatchStatistic__c> goalStats = [
            SELECT Match__c, Team__c, ShotPosition__c, ShotResistance__c, Minute__c, Assist__c, CornerOrFreeKick__c, Penalti__c
            FROM MatchStatistic__c
            WHERE Match__c IN :matchIds AND EventType__c = 'Shot'
        ];
        // Create list with inserting statistic of team goals
        for (MatchStatistic__c ms: goalStats) {
            // Add details of goal if it scored after teammates pass
            if (ms.Assist__c) {
                teamGoalsList.add(new TeamGoals__c(
                    Match__c = ms.Match__c, Team__c = ms.Team__c, Minute__c = ms.Minute__c, OpponentResistance__c = ms.ShotResistance__c,
                    PlayerPosition__c = ms.ShotPosition__c, GoalDetails__c = 'Goal After Teammate Pass'));
            }
            // Add details of goal if it scored after corner or free kick
            if (ms.CornerOrFreeKick__c) {
                teamGoalsList.add(new TeamGoals__c(
                    Match__c = ms.Match__c, Team__c = ms.Team__c, Minute__c = ms.Minute__c, OpponentResistance__c = ms.ShotResistance__c,
                    PlayerPosition__c = ms.ShotPosition__c, GoalDetails__c = 'Goal After Corner Or Fre Kick'));
            }
            // Add details of goal if it scored after penalty 
            if (ms.Penalti__c) {
                teamGoalsList.add(new TeamGoals__c(
                    Match__c = ms.Match__c, Team__c = ms.Team__c, Minute__c = ms.Minute__c, OpponentResistance__c = ms.ShotResistance__c,
                    PlayerPosition__c = ms.ShotPosition__c, GoalDetails__c = 'Goal After Penalty Kick'));
            } if(ms.Assist__c == false && ms.CornerOrFreeKick__c == false && ms.Penalti__c == false) {
                teamGoalsList.add(new TeamGoals__c(
                Match__c = ms.Match__c, Team__c = ms.Team__c, Minute__c = ms.Minute__c, OpponentResistance__c = ms.ShotResistance__c,
                PlayerPosition__c = ms.ShotPosition__c));
            } 
        }
        // Insert team goals statistic
        insert teamGoalsList;
    }
}