force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <label>Match</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/HomeTeam__c.field-meta.xml
<CustomField>
    <fullName>HomeTeam__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Home Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Hosts</relationshipLabel>
    <relationshipName>Hosts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Visitors__c.field-meta.xml
<CustomField>
    <fullName>Visitors__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Visitor Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Visitor</relationshipLabel>
    <relationshipName>Visitor</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>    
</CustomObject>

force-app/main/default/objects/TeamStatistic__c/TeamStatistic__c.object-meta.xml
<CustomObject>
    <description>Statistics of teams played matches</description>
    <label>TeamStatistic</label>
    <nameField>
        <displayFormat>TeamStatistic - {000000}</displayFormat>
        <label>TeamStatistic</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TeamStatistics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TeamStatistic__c/fields/Fouls__c.field-meta.xml
<CustomField>
    <fullName>Fouls__c</fullName>
    <description>Number of fouls completed by team in the match</description>
    <label>Fouls</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/fields/Match__c.field-meta.xml
<CustomField>
    <fullName>Match__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Match</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>Match__c.HomeTeam__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>Match__c.Visitors__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Match__c</referenceTo>
    <relationshipLabel>TeamStatistics</relationshipLabel>
    <relationshipName>TeamStatistics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/fields/RedCard__c.field-meta.xml
<CustomField>
    <fullName>RedCard__c</fullName>
    <description>Number of received red cards in the match</description>
    <label>Red Card</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>TeamStatistics</relationshipLabel>
    <relationshipName>TeamStatistics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TeamStatistic__c/fields/YellowCard__c.field-meta.xml
<CustomField>
    <fullName>YellowCard__c</fullName>
    <description>Number of received yellow cards in the match</description>
    <label>Yellow Card</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/teamDiscipline.cls
public inherited sharing class teamDiscipline {
    @AuraEnabled(cacheable=true)
    public static List<TeamStatistic__c> getTeamFoulsStat(String matchId) {
        // Find home team and visitor team for curent match
        Match__c match = [
            SELECT HomeTeam__c, Visitors__c
            FROM Match__c
            WHERE Id = :matchId
        ];
        // Get Id`s of match participated teams
        String homeTeam = match.HomeTeam__c;
        String visitorTeam = match.Visitors__c;
        // Find statistic of fouls and cards for each team
        List<TeamStatistic__c> teamStats = [
            SELECT Id, Team__r.Name, Match__r.Name, Fouls__c, YellowCard__c, RedCard__c 
            FROM TeamStatistic__c
            WHERE Team__c = :homeTeam OR Team__c = :visitorTeam
            ORDER BY Team__c DESC
            LIMIT 10
        ];        
        return teamStats;
    }
}