force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <label>Match</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/HomeTeam__c.field-meta.xml
<CustomField>
    <fullName>HomeTeam__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Home Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Hosts</relationshipLabel>
    <relationshipName>Hosts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Referee__c.field-meta.xml
<CustomField>
    <fullName>Referee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Match Referee</label>
    <referenceTo>Referee__c</referenceTo>
    <relationshipLabel>Ref</relationshipLabel>
    <relationshipName>Ref</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Visitors__c.field-meta.xml
<CustomField>
    <fullName>Visitors__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Visitor Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Visitor</relationshipLabel>
    <relationshipName>Visitor</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MatchStatistic__c/MatchStatistic__c.object-meta.xml
<CustomObject>
    <label>MatchStatistic</label>
    <nameField>
        <displayFormat>MatchStatistic - {000000}</displayFormat>
        <label>MatchStatistic</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MatchStatistics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MatchStatistic__c/fields/EventType__c.field-meta.xml
<CustomField>
    <fullName>EventType__c</fullName>
    <label>Type of Event</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Shot</fullName>
            </value>
            <value>
                <fullName>Total Shots</fullName>
            </value>
            <value>
                <fullName>Shots On Target</fullName>
            </value>
            <value>
                <fullName>Possesion</fullName>
                <default>true</default>
                <label>Possesion</label>
            </value>
            <value>
                <fullName>Total Passes</fullName>
            </value>
            <value>
                <fullName>Completed Passes</fullName>
            </value>
            <value>
                <fullName>Fouls</fullName>
            </value>
            <value>
                <fullName>Yellow Card</fullName>
            </value>
            <value>
                <fullName>Red Card</fullName>
            </value>
            <value>
                <fullName>Offsides</fullName>
            </value>
            <value>
                <fullName>Corners</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MatchStatistic__c/fields/EventValue__c.field-meta.xml
<CustomField>
    <fullName>EventValue__c</fullName>
    <label>Value of statistical index</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MatchStatistic__c/fields/Match__c.field-meta.xml
<CustomField>
    <fullName>Match__c</fullName>
    <label>Match</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>You should choose team that participate in this match.</errorMessage>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>Match__c.HomeTeam__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>Match__c.Visitors__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Match__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MatchStatistic__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referee__c/Referee__c.object-meta.xml
<CustomObject>
    <label>Referee</label>
    <nameField>
        <label>Referee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referees</pluralLabel>
    <sharingModel>Private</sharingModel>    
</CustomObject>

force-app/main/default/objects/Referee__c/fields/Fouls__c.field-meta.xml
<CustomField>
    <fullName>Fouls__c</fullName>
    <label>Fouls Recorded Per Game</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Referee__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Referee Name</label>    
    <required>true</required>
    <type>Text</type>
    <length>36</length>
</CustomField>

force-app/main/default/objects/Referee__c/fields/RedCards__c.field-meta.xml
<CustomField>
    <fullName>RedCards__c</fullName>
    <label>Red Cards Show Per Game</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Referee__c/fields/YellowCards__c.field-meta.xml
<CustomField>
    <fullName>YellowCards__c</fullName>
    <label>Yellow Cards Show Per Game</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>    
</CustomObject>

force-app/main/default/objects/Team__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Team Name</label>    
    <required>true</required>
    <type>Text</type>
    <length>68</length>
</CustomField>

force-app/main/default/classes/MatchDAO.cls
public class MatchDAO {
    // Method return list of referee for curent match
    public static List<Referee__c> refereeList(Id matchId) {
        // Find referee for curent match
        Match__c m = [
            SELECT Referee__c
            FROM Match__c
            WHERE Id = :matchId 
        ];
        // Get the referee Id
        Id refId = m.Referee__c;
        // Find referee information and statistic 
        List<Referee__c> ref = [
            SELECT Name__c, Fouls__c, YellowCards__c, RedCards__c
            FROM Referee__c
            WHERE Id = :refId 
        ];
        return ref;
    }

    // Method return type of statisic indexes for curent match
    @AuraEnabled
    public static List<MatchStatistic__c> getEventTypeList(Id matchId) {
        Match__c match = [
            SELECT Visitors__c 
            FROM Match__c 
            WHERE Id = :matchId];        
        String team = match.Visitors__c;
        // Find type of statistic index for curent match
        List<MatchStatistic__c> eventTypeList = [
            SELECT EventType__c
            FROM MatchStatistic__c
            WHERE Match__c = :matchId AND Team__c = :team AND EventType__c != 'Shot'
            ORDER BY EventType__c ASC
        ];
        return eventTypeList;
    }

    // Method return value of statisic indexes for home team
    @AuraEnabled
    public static List<MatchStatistic__c> getHomeStat(Id matchId) {
        // Find home team for curent match
        Match__c match = [
            SELECT HomeTeam__c 
            FROM Match__c 
            WHERE Id = :matchId];
        // Get Id of match home team    
        String team = match.HomeTeam__c;
        // Find type and value of statistic indexes of home team for curent match
        List<MatchStatistic__c> stat = [
            SELECT EventType__c, EventValue__c
            FROM MatchStatistic__c
            WHERE Match__c = :matchId AND Team__c = :team AND EventType__c != 'Shot'
            ORDER BY EventType__c ASC
        ];
        return stat;
    }

    // Method return value of statisic indexes for visitor team 
    @AuraEnabled
    public static List<MatchStatistic__c> getVisitorStat(Id matchId) {
        // Find visitor team for curent match
        Match__c match = [
            SELECT Visitors__c 
            FROM Match__c 
            WHERE Id = :matchId];
        // Get Id of match visitor team
        String team = match.Visitors__c;
        // Find type and value of statistic indexes of visitor team for curent match
        List<MatchStatistic__c> stat = [
            SELECT EventType__c, EventValue__c
            FROM MatchStatistic__c
            WHERE Match__c = :matchId AND Team__c = :team AND EventType__c != 'Shot'
            ORDER BY EventType__c ASC
        ];
        return stat;
    }

    // Method return names of match participated teams for aura component header
    @AuraEnabled
    public static List<Match__c> getMatchTeams(Id matchId) {
        // Find names of match participated teams
        List<Match__c> matchTeams = [
            SELECT Name, HomeTeam__r.Name, Visitors__r.Name
            FROM Match__c
            WHERE Id = :matchId
        ];
        return matchTeams;
    }

}